# Generated by Django 6.0 on 2025-12-24 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField(help_text='Push service endpoint URL', unique=True)),
                ('p256dh_key', models.TextField(help_text='User public key for encryption (p256dh)')),
                ('auth_key', models.TextField(help_text='User auth secret for encryption')),
                ('user_agent', models.TextField(blank=True, help_text='Browser/device info')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='Optional: Link to authenticated user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'push_subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('icon', models.URLField(blank=True)),
                ('url', models.URLField(blank=True, help_text='URL to open when clicked')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='notifications.pushsubscription')),
            ],
            options={
                'db_table': 'notification_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.AddIndex(
            model_name='pushsubscription',
            index=models.Index(fields=['endpoint'], name='push_subscr_endpoin_48e896_idx'),
        ),
        migrations.AddIndex(
            model_name='pushsubscription',
            index=models.Index(fields=['user', 'is_active'], name='push_subscr_user_id_c81a15_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['subscription', '-created_at'], name='notificatio_subscri_d89a96_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['status'], name='notificatio_status_95b675_idx'),
        ),
    ]
