# Generated by Django 6.0 on 2025-12-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadableResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='downloads/')),
                ('category', models.CharField(choices=[('doc', 'Documents'), ('img', 'Images'), ('video', 'Videos'), ('audio', 'Audio'), ('archive', 'Archives'), ('other', 'Other')], default='other', max_length=20)),
                ('size', models.CharField(help_text="e.g., '45.2 MB'", max_length=20)),
                ('downloads', models.IntegerField(default=0)),
                ('version', models.CharField(default='v1.0.0', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='MUI Icon name', max_length=50)),
                ('path', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('popularity', models.IntegerField(default=0)),
                ('tags', models.JSONField(default=list)),
                ('color', models.CharField(default='primary', help_text='MUI Color palette name', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
