# Generated by Django 6.0 on 2025-12-23 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_useractivity_execution_time_useractivity_ip_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAnalysis',
            fields=[
            ],
            options={
                'verbose_name': 'Log Analysis',
                'verbose_name_plural': 'Log Analysis',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('services.service',),
        ),
    ]
