# Generated by Django 6.0 on 2025-12-27 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_serverhealth'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadableresource',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='downloads/covers/'),
        ),
        migrations.AddField(
            model_name='downloadableresource',
            name='description',
            field=models.TextField(blank=True, help_text='Full description of the resource'),
        ),
        migrations.AddField(
            model_name='downloadableresource',
            name='keywords',
            field=models.CharField(blank=True, help_text='Comma-separated SEO keywords', max_length=255),
        ),
        migrations.AddField(
            model_name='downloadableresource',
            name='seo_description',
            field=models.CharField(blank=True, help_text='SEO meta description (optional)', max_length=160),
        ),
        migrations.AddField(
            model_name='downloadableresource',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Custom SEO title (optional)', max_length=100),
        ),
        migrations.AddField(
            model_name='downloadableresource',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier', max_length=255, null=True),
        ),
    ]
