# Generated by Django 6.0 on 2025-12-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_downloadableresource_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadableresource',
            name='slug',
            field=models.SlugField(default='', help_text='URL-friendly identifier', max_length=255, unique=True),
        ),
    ]
