# Generated by Django 6.0 on 2025-12-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_downloadableresource_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadableresource',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier', max_length=255, unique=True),
        ),
    ]
