# Generated by Django 6.0 on 2026-02-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('inquiry_type', models.CharField(choices=[('general', 'General Contact'), ('hire', 'Hire Developer'), ('support', 'Support'), ('feedback', 'Feedback'), ('partnership', 'Partnership')], default='general', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('project_type', models.CharField(blank=True, help_text='For hire inquiries', max_length=100)),
                ('budget', models.CharField(blank=True, help_text='Budget range for project', max_length=50)),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('replied', 'Replied'), ('closed', 'Closed')], default='new', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('source_page', models.CharField(blank=True, help_text='Which page the form was submitted from', max_length=50)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes about this inquiry')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Inquiry',
                'verbose_name_plural': 'Contact Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
