# Generated by Django 6.0 on 2025-12-21 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_useractivity_favoritetool'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='execution_time',
            field=models.FloatField(blank=True, help_text='Execution time in seconds', null=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial')], default='success', max_length=20),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DownloadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_type', models.CharField(choices=[('youtube', 'YouTube Video'), ('url', 'URL Download'), ('image', 'Image'), ('resource', 'Downloadable Resource'), ('other', 'Other')], max_length=20)),
                ('url', models.URLField(max_length=500)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('file_size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('format', models.CharField(blank=True, max_length=20)),
                ('quality', models.CharField(blank=True, help_text='e.g., 720p, 1080p', max_length=50)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial')], default='success', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('duration_seconds', models.FloatField(blank=True, help_text='How long the download took', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='download_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Download Histories',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='services_do_created_fffbcd_idx'), models.Index(fields=['user', '-created_at'], name='services_do_user_id_d0c114_idx'), models.Index(fields=['download_type'], name='services_do_downloa_1b86d5_idx'), models.Index(fields=['status'], name='services_do_status_719611_idx')],
            },
        ),
    ]
