# Generated by Django 6.0 on 2025-12-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_loganalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogIntelligence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, unique=True)),
                ('state_data', models.JSONField(help_text='Full aggregated state of log analysis')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Log Intelligence State',
                'verbose_name_plural': 'Log Intelligence States',
                'ordering': ['-date'],
            },
        ),
    ]
