# Generated by Django 6.0 on 2025-12-23 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_logintelligence'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerHealth',
            fields=[
            ],
            options={
                'verbose_name': 'Server Health',
                'verbose_name_plural': 'Server Health',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('services.service',),
        ),
    ]
