# Generated by Django 6.0 on 2025-12-29 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_downloadableresource_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(db_index=True, help_text="Logical tool name e.g. 'qr-generator'", max_length=120)),
                ('endpoint', models.CharField(blank=True, help_text='Request path e.g. /api/services/qr-generator/', max_length=255)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('forwarded_for', models.TextField(blank=True, help_text='Raw X-Forwarded-For header')),
                ('user_agent', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial')], db_index=True, default='success', max_length=20)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('execution_time_ms', models.IntegerField(blank=True, null=True)),
                ('request_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tool_name', '-created_at'], name='services_to_tool_na_e21fb4_idx'), models.Index(fields=['user', '-created_at'], name='services_to_user_id_90e1eb_idx'), models.Index(fields=['ip_address', '-created_at'], name='services_to_ip_addr_ca4efd_idx'), models.Index(fields=['status', '-created_at'], name='services_to_status_3ca650_idx')],
            },
        ),
    ]
