# Generated by Django 6.0.1 on 2026-04-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_webhookendpoint_webhookrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='requires_login',
            field=models.BooleanField(default=False, help_text='If checked, only authenticated users can use this tool'),
        ),
    ]
