# Generated by Django 6.0.6 on 2026-07-04 21:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_add_uptime_robot_service'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UptimeMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('monitor_type', models.CharField(choices=[('http', 'HTTP(S)'), ('keyword', 'Keyword Match'), ('ping', 'Ping (TCP connect)'), ('port', 'Port Check'), ('ssl', 'SSL Certificate'), ('heartbeat', 'Heartbeat Listener')], default='http', max_length=20)),
                ('target', models.CharField(blank=True, help_text='URL or hostname; not used for heartbeat monitors', max_length=500)),
                ('keyword', models.CharField(blank=True, max_length=200)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('interval_minutes', models.IntegerField(default=5)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused')], default='active', max_length=10)),
                ('heartbeat_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(default='never', max_length=10)),
                ('last_latency_ms', models.IntegerField(default=0)),
                ('logs', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uptime_monitors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
