# Generated by Django 6.0.6 on 2026-07-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_uptimemonitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoKeywordOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(help_text='Route path, e.g. /services/hash-generator', max_length=200, unique=True)),
                ('keywords', models.JSONField(blank=True, default=list, help_text='List of keyword strings, e.g. ["free hash generator", "sha256 online"]')),
                ('title', models.CharField(blank=True, help_text="Leave blank to keep the page's default title", max_length=200)),
                ('description', models.TextField(blank=True, help_text="Leave blank to keep the page's default description")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['route'],
            },
        ),
    ]
