# Generated by Django 6.0 on 2025-12-21 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Uploaded image file', upload_to='ai_detector/%Y/%m/%d/')),
                ('filename', models.CharField(help_text='Original filename', max_length=255)),
                ('is_ai_generated', models.BooleanField(default=False, help_text='Whether the image is detected as AI-generated')),
                ('confidence', models.FloatField(default=0.0, help_text='Confidence score (0-100)')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Stores EXIF data, image stats, ELA results, and all detection scores')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who uploaded the image (null for anonymous)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Image Analysis',
                'verbose_name_plural': 'Image Analyses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='ai_detector_created_89d3f1_idx'), models.Index(fields=['user', '-created_at'], name='ai_detector_user_id_f085c4_idx')],
            },
        ),
    ]
