# Generated by Django 6.0.6 on 2026-07-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinquiry',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact number for call-back inquiries (e.g. from the chatbot)', max_length=30),
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='email',
            field=models.EmailField(blank=True, help_text='Optional if a phone number is provided instead', max_length=254),
        ),
    ]
