# Generated by Django 6.0.6 on 2026-08-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0002_contactinquiry_phone_alter_contactinquiry_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactinquiry",
            name="notification_sent",
            field=models.BooleanField(
                default=False,
                help_text="Whether the admin notification email for this inquiry was sent successfully",
            ),
        ),
    ]
