import React, { useState, useRef, useCallback, useEffect } from 'react';
import {
    Box, Card, Typography, Grid, Paper, Stack, Button, Chip, Alert, useTheme,
} from '@mui/material';
import { Compare, PlayArrow, CheckCircle } from '@mui/icons-material';
import ServicePageShell from './ServicePageShell';

// Minimal valid WASM module: exports `add(i32, i32) -> i32`.
// Hand-assembled per the WebAssembly binary format spec (this is the
// canonical minimal "add" module structure documented across WASM
// tutorials/MDN) - not generated by a compiler, since no WASM toolchain
// is available at runtime in the browser.
//
// The code section's body is 7 bytes (local-decl-count byte, two 2-byte
// local.get ops, 1-byte i32.add, 1-byte end), so both the body-size byte
// and the code-section size byte below account for 7, not 6 - an easy
// off-by-one to get wrong by hand. Verified by actually instantiating
// this exact array with WebAssembly.instantiate() in Node before use, not
// just eyeballed against the spec.
const WASM_ADD_MODULE_BYTES = new Uint8Array([
    0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00, // magic "\0asm", version 1
    0x01, 0x07, 0x01, 0x60, 0x02, 0x7f, 0x7f, 0x01, 0x7f, // type section: (i32,i32)->i32
    0x03, 0x02, 0x01, 0x00, // function section: 1 function, uses type 0
    0x07, 0x07, 0x01, 0x03, 0x61, 0x64, 0x64, 0x00, 0x00, // export section: "add" -> func 0
    0x0a, 0x09, 0x01, 0x07, 0x00, 0x20, 0x00, 0x20, 0x01, 0x6a, 0x0b, // code: local.get 0; local.get 1; i32.add; end
]);

// Same shape as the WASM export, for a fair comparison.
function jsAdd(a: number, b: number): number {
    return a + b;
}

const BENCH_DURATION_MS = 1500;
const CHECK_INTERVAL = 100_000; // check elapsed time every N iterations, not every call

type WasmAddFn = (a: number, b: number) => number;

type WasmStatus =
    | { state: 'checking' }
    | { state: 'ready' }
    | { state: 'unsupported'; message: string };

interface BenchRun {
    callsPerSec: number;
    iterations: number;
    checksum: number;
}

interface BenchmarkResults {
    js: BenchRun;
    wasm: BenchRun;
    faster: 'js' | 'wasm' | 'tie';
    factor: number;
}

function runTightLoop(fn: WasmAddFn, durationMs: number): BenchRun {
    const start = performance.now();
    let acc = 0;
    let iterations = 0;
    let elapsed = 0;
    for (;;) {
        for (let j = 0; j < CHECK_INTERVAL; j++) {
            // Masking keeps the accumulator bounded (important for the wasm
            // i32 side) while still forcing every call's result to be read,
            // so the engine can't drop the calls as dead code.
            acc = fn(acc, 1) & 0xffff;
        }
        iterations += CHECK_INTERVAL;
        elapsed = performance.now() - start;
        if (elapsed >= durationMs) break;
    }
    return { callsPerSec: elapsed > 0 ? iterations / (elapsed / 1000) : 0, iterations, checksum: acc };
}

function formatRate(n: number): string {
    if (!isFinite(n) || n <= 0) return '--';
    if (n >= 1_000_000_000) return `${(n / 1_000_000_000).toFixed(2)}B/sec`;
    if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(2)}M/sec`;
    if (n >= 1_000) return `${(n / 1_000).toFixed(1)}K/sec`;
    return `${n.toFixed(0)}/sec`;
}

function StatTile({ label, value, accent }: { label: string; value: string; accent?: boolean }) {
    const theme = useTheme();
    return (
        <Paper sx={{
            p: 2, textAlign: 'center', borderRadius: 2,
            bgcolor: accent ? 'rgba(255,255,255,0.04)' : 'rgba(255,255,255,0.02)',
            border: `1px solid ${accent ? theme.palette.primary.main : 'rgba(255,255,255,0.08)'}`,
        }}>
            <Typography variant="caption" color="text.secondary" sx={{ textTransform: 'uppercase', letterSpacing: 0.5, display: 'block' }}>
                {label}
            </Typography>
            <Typography variant="h5" fontWeight={800}>{value}</Typography>
        </Paper>
    );
}

const WasmVsJsBenchmark: React.FC = () => {
    const [wasmStatus, setWasmStatus] = useState<WasmStatus>({ state: 'checking' });
    const [running, setRunning] = useState(false);
    const [results, setResults] = useState<BenchmarkResults | null>(null);

    const wasmAddRef = useRef<WasmAddFn | null>(null);

    useEffect(() => {
        let cancelled = false;

        async function init() {
            if (typeof WebAssembly === 'undefined') {
                if (!cancelled) setWasmStatus({ state: 'unsupported', message: 'WebAssembly is not available in this browser.' });
                return;
            }
            try {
                const { instance } = await WebAssembly.instantiate(WASM_ADD_MODULE_BYTES);
                const add = instance.exports.add as WasmAddFn;
                const check = add(2, 3);
                if (check !== 5) {
                    throw new Error(`Sanity check failed: add(2, 3) returned ${check}, expected 5.`);
                }
                wasmAddRef.current = add;
                if (!cancelled) setWasmStatus({ state: 'ready' });
            } catch (e) {
                if (!cancelled) {
                    setWasmStatus({
                        state: 'unsupported',
                        message: e instanceof Error ? e.message : 'Failed to load the WebAssembly module in this browser.',
                    });
                }
            }
        }

        init();
        return () => { cancelled = true; };
    }, []);

    const runBenchmark = useCallback(async () => {
        const wasmAdd = wasmAddRef.current;
        if (!wasmAdd) return;

        setRunning(true);
        setResults(null);

        // Yield two frames so the "Running…" state actually paints before
        // the tight loops below block the main thread.
        await new Promise<void>((resolve) => {
            requestAnimationFrame(() => requestAnimationFrame(() => resolve()));
        });

        const js = runTightLoop(jsAdd, BENCH_DURATION_MS);

        // Brief yield between the two blocking loops.
        await new Promise<void>((resolve) => setTimeout(resolve, 0));

        const wasm = runTightLoop(wasmAdd, BENCH_DURATION_MS);

        let faster: 'js' | 'wasm' | 'tie' = 'tie';
        let factor = 1;
        if (js.callsPerSec > wasm.callsPerSec) {
            faster = 'js';
            factor = wasm.callsPerSec > 0 ? js.callsPerSec / wasm.callsPerSec : 0;
        } else if (wasm.callsPerSec > js.callsPerSec) {
            faster = 'wasm';
            factor = js.callsPerSec > 0 ? wasm.callsPerSec / js.callsPerSec : 0;
        }

        setResults({ js, wasm, faster, factor });
        setRunning(false);
    }, []);

    const about = "This benchmark measures a specific, often-misunderstood number: how many times per second your browser can call a function across the JavaScript-to-WebAssembly boundary, compared to calling an equivalent plain JavaScript function, for the simplest possible operation of adding two integers. On load it compiles a tiny hand-verified WASM module exporting one add function and runs a sanity check (add(2, 3) must return 5) before letting you run anything. The actual test runs each version in a tight loop for 1.5 seconds, accumulating every result so the engine can't optimize the calls away as unused work, then reports real calls-per-second for both. This measures call overhead plus a trivial op, not the kind of compute-heavy workload where WebAssembly usually pulls ahead (see the CPU Load Test's matrix multiply for that side of the story).";

    const howToSteps = [
        { name: 'Wait for the sanity check', text: 'On page load the tool compiles a minimal WASM module and verifies add(2, 3) returns 5 before the Run button becomes available.' },
        { name: 'Click Run Benchmark', text: 'Both loops run one after another, about 1.5 seconds each. The tab will feel unresponsive during that window since each loop intentionally blocks the main thread for accurate timing.' },
        { name: 'Compare calls per second', text: 'The result shows raw calls/sec for JavaScript and WebAssembly side by side, plus which one came out faster in your browser and by how much.' },
    ];

    const faq = [
        {
            question: "Doesn't WebAssembly always beat JavaScript?",
            answer: 'No, and this benchmark is a good example of why. It only measures function-call overhead plus a single trivial addition. WebAssembly\'s real performance advantage shows up in larger, compute-bound workloads like numeric loops, image processing, or physics simulation, not in a single add call.',
        },
        {
            question: 'Why might JavaScript come out faster here?',
            answer: "V8 and other modern JS engines can inline a tiny hot function like jsAdd directly into the calling loop, removing the call overhead almost entirely. Crossing the JS-to-WASM boundary carries its own fixed cost per call, and for something this small that cost can end up larger than what the JIT-optimized JS path pays. This is a real, well-documented effect, not a flaw in the test.",
        },
        {
            question: 'Is the WebAssembly module actually running, or is this faked?',
            answer: 'It is a real, minimal compiled WASM module (16 bytes of module structure) loaded with WebAssembly.instantiate and exercised through its actual exported function. The sanity check that gates the Run button confirms it returns the correct result before any timing starts.',
        },
        {
            question: 'Why does my tab freeze for a few seconds when I click Run?',
            answer: 'That is intentional. Each loop blocks the main thread on purpose so the timing measurement is not disturbed by other work competing for the thread.',
        },
        {
            question: 'What is the checksum for?',
            answer: "It's the accumulated result of every call in the loop. Without reading that value, a sufficiently aggressive optimizer could notice the loop's output is never used and delete the whole thing, which would make the benchmark measure nothing.",
        },
    ];

    return (
        <ServicePageShell
            icon={Compare}
            title="WebAssembly vs JavaScript Benchmark"
            subtitle="Real calls-per-second throughput: a WASM export vs. an equivalent JS function"
            maxWidth="sm"
            toolId={90}
            seoTitle="WebAssembly vs JavaScript Speed Test | Real Call Overhead Benchmark"
            seoDescription="Measure real calls-per-second throughput for a WebAssembly function vs. an equivalent JavaScript function, directly in your browser."
            keywords={['webassembly vs javascript', 'wasm benchmark', 'wasm vs js performance', 'webassembly speed test', 'js call overhead', 'wasm call overhead benchmark']}
            about={about}
            howToSteps={howToSteps}
            faq={faq}
        >
            <Card sx={{
                background: 'rgba(13, 14, 18, 0.4)',
                backdropFilter: 'blur(20px)',
                border: '1px solid rgba(255,255,255,0.05)',
                borderRadius: '20px',
                boxShadow: '0 20px 40px -15px rgba(0,0,0,0.5)',
                p: 3,
                flex: 1,
                minHeight: 0,
                overflowY: 'auto',
            }}>
                <Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between" alignItems={{ sm: 'center' }} spacing={2} sx={{ mb: 3 }}>
                    <Box>
                        <Typography variant="h6" fontWeight={700}>Call Overhead Benchmark</Typography>
                        {wasmStatus.state === 'checking' && (
                            <Typography variant="body2" color="text.secondary">Verifying the WASM module…</Typography>
                        )}
                        {wasmStatus.state === 'ready' && (
                            <Stack direction="row" spacing={0.5} alignItems="center">
                                <CheckCircle fontSize="small" color="success" />
                                <Typography variant="body2" color="text.secondary">WASM sanity check passed: add(2, 3) = 5</Typography>
                            </Stack>
                        )}
                        {wasmStatus.state === 'unsupported' && (
                            <Typography variant="body2" color="error.main">{wasmStatus.message}</Typography>
                        )}
                    </Box>
                    <Button
                        variant="contained"
                        startIcon={<PlayArrow />}
                        onClick={runBenchmark}
                        disabled={wasmStatus.state !== 'ready' || running}
                    >
                        {running ? 'Running…' : results ? 'Run Again' : 'Run Benchmark'}
                    </Button>
                </Stack>

                {wasmStatus.state === 'unsupported' && (
                    <Alert severity="error" sx={{ mb: 3 }}>
                        WebAssembly is not supported or failed to load in this browser, so this benchmark can't run here.
                    </Alert>
                )}

                {running && (
                    <Alert severity="info" sx={{ mb: 3 }}>
                        Running both loops now (about 3 seconds total). This tab may be briefly unresponsive, that's expected since each loop blocks the main thread on purpose for accurate timing.
                    </Alert>
                )}

                {results && !running && (
                    <Box>
                        <Box sx={{ textAlign: 'center', mb: 3 }}>
                            <Typography variant="overline" color="text.secondary">Result</Typography>
                            <Typography variant="h4" fontWeight={900} sx={{ my: 0.5 }}>
                                {results.faster === 'tie'
                                    ? 'JavaScript and WebAssembly measured the same'
                                    : `${results.faster === 'js' ? 'JavaScript' : 'WebAssembly'} is ${results.factor.toFixed(2)}x faster`}
                            </Typography>
                            <Typography variant="body2" color="text.secondary">for this call pattern, in this browser, right now</Typography>
                        </Box>

                        <Grid container spacing={2} sx={{ mb: 2 }}>
                            <Grid item xs={6}>
                                <StatTile label="JavaScript" value={formatRate(results.js.callsPerSec)} accent={results.faster === 'js'} />
                            </Grid>
                            <Grid item xs={6}>
                                <StatTile label="WebAssembly" value={formatRate(results.wasm.callsPerSec)} accent={results.faster === 'wasm'} />
                            </Grid>
                        </Grid>

                        <Stack direction="row" spacing={1} flexWrap="wrap" useFlexGap justifyContent="center">
                            <Chip size="small" variant="outlined" label={`JS iterations: ${results.js.iterations.toLocaleString()}`} />
                            <Chip size="small" variant="outlined" label={`WASM iterations: ${results.wasm.iterations.toLocaleString()}`} />
                            <Chip size="small" variant="outlined" label={`Checksums: ${results.js.checksum} / ${results.wasm.checksum}`} />
                        </Stack>
                    </Box>
                )}
            </Card>
        </ServicePageShell>
    );
};

export default WasmVsJsBenchmark;
